name: Build and Test
run-name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: admin
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"

      - name: Configure Turbo cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Restore cached node_modules
        id: cache-node-modules-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - run: "yarn install"
      - name: "Check that yarn install did not cause changes to yarn.lock"
        run: "git diff --quiet -- yarn.lock"
      - run: "yarn check-references"
      - run: "yarn build"
      - run: "yarn lint"
      - run: "yarn test"
      - name: "Test that template package works out-of-the-box"
        run: "yarn test-generated-package"

      - name: Save cached node_modules
        id: cache-primes-save
        uses: actions/cache/save@v4
        with:
          path: |
            **/node_modules
            some/other/dependencies
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
